#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

// Set 0 : UBO caméra
layout(set = 0, binding = 0) uniform global_uniform_object {
    mat4 view;
    mat4 projection;
    float time;
} global_ubo;

// Set 1 : buffers par VoxelBuffer
struct ChunkCullData {
    vec4 aabbMin;
    vec4 aabbMax;
    uint vertexCount;
    uint instanceCount;
    uint firstVertex;
    uint firstInstance;
    uint padding;
};

struct DrawIndirectCommand {
    uint vertexCount;
    uint instanceCount;
    uint firstVertex;
    uint firstInstance;
};

layout(set = 1, binding = 0, std430) readonly buffer ChunkCullDataBuffer {
    ChunkCullData chunks[];
};

layout(set = 1, binding = 1, std430) writeonly buffer CulledIndirectBuffer {
    DrawIndirectCommand culledCommands[];
};

layout(set = 1, binding = 2, std430) buffer CulledDrawCountBuffer {
    uint culledCount;
};

layout(push_constant) uniform PushConstants {
    uint chunkCount;
} pc;

void extract_frustum_planes(mat4 vp, out vec4 planes[6]) {
    planes[0] = vec4(vp[0][3] + vp[0][0], vp[1][3] + vp[1][0], vp[2][3] + vp[2][0], vp[3][3] + vp[3][0]); // left
    planes[1] = vec4(vp[0][3] - vp[0][0], vp[1][3] - vp[1][0], vp[2][3] - vp[2][0], vp[3][3] - vp[3][0]); // right
    planes[2] = vec4(vp[0][3] + vp[0][1], vp[1][3] + vp[1][1], vp[2][3] + vp[2][1], vp[3][3] + vp[3][1]); // bottom
    planes[3] = vec4(vp[0][3] - vp[0][1], vp[1][3] - vp[1][1], vp[2][3] - vp[2][1], vp[3][3] - vp[3][1]); // top
    planes[4] = vec4(vp[0][3] + vp[0][2], vp[1][3] + vp[1][2], vp[2][3] + vp[2][2], vp[3][3] + vp[3][2]); // near
    planes[5] = vec4(vp[0][3] - vp[0][2], vp[1][3] - vp[1][2], vp[2][3] - vp[2][2], vp[3][3] - vp[3][2]); // far
}

bool is_aabb_visible(vec3 aabbMin, vec3 aabbMax, vec4 planes[6]) {
    for (int i = 0; i < 6; i++) {
        vec3 n = planes[i].xyz;
        vec3 pVertex = vec3(
        n.x >= 0.0 ? aabbMax.x : aabbMin.x,
        n.y >= 0.0 ? aabbMax.y : aabbMin.y,
        n.z >= 0.0 ? aabbMax.z : aabbMin.z
        );
        if (dot(n, pVertex) + planes[i].w < 0.0) {
            return false;
        }
    }
    return true;
}

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= pc.chunkCount) return;

    ChunkCullData chunk = chunks[idx];

    // Nothing to draw, skip
    // if (chunk.instanceCount == 0) return;

    mat4 vp = global_ubo.projection * global_ubo.view;
    vec4 planes[6];
    extract_frustum_planes(vp, planes);

//    if (!is_aabb_visible(chunk.aabbMin.xyz, chunk.aabbMax.xyz, planes)) return;

    // Increment the count of visible chunks and write the indirect draw command
    uint outIdx = atomicAdd(culledCount, 1);

    culledCommands[outIdx] = DrawIndirectCommand(
        chunk.vertexCount,
        chunk.instanceCount,
        chunk.firstVertex,
        chunk.firstInstance
    );
}
