add_library(VoxelPlanetRenderer STATIC
        vulkan/VulkanBackend.cpp
        vulkan/VulkanBackend.h
        RendererModule.cpp
        RendererModule.h
        Renderer.h
        vulkan/vulkan_type.inl
        debug/ImGuiManager.h
        debug/ImGuiManager.cpp
        world/VoxelBuffer.cpp
        world/VoxelBuffer.h
        render_types.h
        IRenderPass.h
        world/VoxelTextureManager.cpp
        world/VoxelTextureManager.h
        TracyVulkanIntegration.h
        world/VoxelMeshUploadBatcher.cpp
        world/VoxelMeshUploadBatcher.h
        debug/DebugDrawRenderer.cpp
        debug/DebugDrawRenderer.h
        world/planet/PlanetRenderModule.cpp
        world/planet/PlanetRenderModule.h
        camera/Camera3dModule.cpp
        camera/Camera3dModule.h
        camera/camera3d_systems.h
        debug/DebugRenderModule.cpp
        debug/DebugRenderModule.h
        world/planet/PlanetSurfaceTerrainRenderer.cpp
        world/planet/PlanetSurfaceTerrainRenderer.h
        world/planet/PlanetChunkMesher.cpp
        world/planet/PlanetChunkMesher.h
        world/planet/PlanetLodTree.cpp
        world/planet/PlanetLodTree.h
        world/planet/planet_render_types.h
        world/planet/PlanetLodStore.cpp
        world/planet/PlanetLodStore.h
        world/planet/PlanetLodGpuBuffers.cpp
        world/planet/PlanetLodGpuBuffers.h
)

add_library(VoxelPlanet::Renderer ALIAS VoxelPlanetRenderer)

target_include_directories(VoxelPlanetRenderer
        PUBLIC
            ${CMAKE_SOURCE_DIR}/src
)

target_link_libraries(VoxelPlanetRenderer
        PUBLIC
            Vulkan::Vulkan
            vk-bootstrap::vk-bootstrap
            VulkanMemoryAllocator
            glm::glm
            nvrhi_vk
            nvrhi
            imgui
            implot
            flecs::flecs_static
        PRIVATE
            VoxelPlanet::Core
            VoxelPlanet::Platform
            VoxelPlanet::Utils
)